In [1]:
import csv,os
import pandas as pd
import numpy as np
import re

In [2]:
#读入csv中的数据，（导入检索式）
a = []
csv_reader=csv.reader(open(r'C:\Users\rk\Desktop\fawenyuzhi.csv',encoding='GB18030'))#打开文件
for row in csv_reader:
    a.append(row)#将读入的数据赋值给列表a

In [3]:
a[0]

['Subject', 'Institution', 'Pub', 'CNCI', '%IC']

In [4]:
a[1]

['Aerospace Engineering', 'Aalborg University', '3', '0.7127', '33.33333333']

In [5]:
del a[0]

In [6]:
a[0]

['Aerospace Engineering', 'Aalborg University', '3', '0.7127', '33.33333333']

In [7]:
c=[]
for item in a:
    b=[]
    b.append(item[0])
    b.append(item[1:])
    c.append(b)

In [8]:
####################运用此程序的前提是：先在原文件里做好分类汇总####################################
final_lis=[]
counter=0
while True:#为了是for循环中的起始值counter的改变，for进入循环后，起始值不再改变，
    for item_1 in c[counter:]:
        diction=[]
        lis_c=[]
        initial_s=0
        lis_c.append(item_1[1])#将第一个期刊加入列表，在此处加入是防止仅出现一次而忽略
        for item_2 in c[counter+1:]:
            if item_1[0]==item_2[0]:
                lis_c.append(item_2[1])#将相同的期刊加入列表
                initial_s+=1 #每找到一个相同的就把initial_s加一，     
        diction.append(item_1[0])
        diction.append(lis_c)
        final_lis.append(diction)
        break#为了使for循环中的起始值改变，循环一次后利用break强制退出for循环，利用while进入下一次循环
    counter=counter+initial_s+1
    if counter>=len(c):#为了使while循环跳出,当大于列表长度的时候跳出循环
        break

In [9]:
final_lis[0]

['Aerospace Engineering',
 [['Aalborg University', '3', '0.7127', '33.33333333'],
  ['Aalto University', '13', '0.779823077', '46.15384615'],
  ['Aarhus University', '6', '8.66775', '100'],
  ['Abu Dhabi University', '1', '0.5561', '100'],
  ['Academic Center for Dentistry Amsterdam', '3', '1.935033333', '100'],
  ['Academy of Athens', '1', '0.1775', '100'],
  ['Academy of Mathematics & System Sciences, CAS', '1', '1.2115', '100'],
  ['Adam Mickiewicz University', '5', '0.41408', '20'],
  ['Adi Shankara Institute of Engineering & Technology', '1', '0.5048', '0'],
  ['AGH University of Science & Technology', '1', '1.1122', '100'],
  ['Aichi University Education', '1', '0.1533', '100'],
  ['Ain Shams University', '1', '0.2524', '100'],
  ['Air Force Engineering University', '56', '1.193607143', '8.928571429'],
  ['Aix-Marseille Universite', '20', '1.55219', '60'],
  ['Ajou University', '2', '0.44225', '0'],
  ['Akdeniz University', '1', '15.2995', '0'],
  ['Akita University', '3', '0.249033333', '33.33333333'],
  ['Alabama A&M University', '2', '0.44385', '50'],
  ['Aleksandras Stulginskis University', '1', '0', '0'],
  ['Alexandria University', '1', '0', '100'],
  ['Alfred University', '1', '0.4769', '0'],
  ['Alzahra University', '1', '0.8619', '0'],
  ['Ambo University', '1', '2.7765', '100'],
  ['American University of Sharjah', '1', '0.2973', '100'],
  ['Amirkabir University of Technology', '73', '1.171972603', '8.219178082'],
  ['Amity University', '2', '6.79165', '0'],
  ['Amrita Vishwa Vidyapeetham University', '9', '0.259422222', '22.22222222'],
  ['Anadolu University', '24', '0.579833333', '4.166666667'],
  ['Andong National University', '14', '0.524021429', '71.42857143'],
  ['Anglia Ruskin University', '1', '1.53', '0'],
  ['Anhui Agricultural University', '2', '0.153', '100'],
  ['Anhui Polytechnic University', '2', '2.32445', '0'],
  ['Anhui University', '2', '1.7942', '0'],
  ['Anhui University of Technology', '2', '0.50845', '0'],
  ['Ankara University', '1', '0.4183', '100'],
  ['Anna University', '16', '0.2073', '0'],
  ['Anna University Chennai', '15', '0.209166667', '0'],
  ['Anna University of Technology Coimbatore', '1', '0.1793', '0'],
  ['Aoyama Gakuin University', '2', '1.5433', '0'],
  ['Arab Academy for Science, Technology & Maritime Transport',
   '1',
   '2.615',
   '0'],
  ['Ariel University', '2', '1.49135', '0'],
  ['Aristotle University of Thessaloniki', '12', '1.117175', '58.33333333'],
  ['Arizona State University', '32', '2.36129375', '18.75'],
  ['Army Medical University', '1', '0.2978', '0'],
  ['ASPETE - School of Pedagogical & Technological Education',
   '1',
   '2.2245',
   '0'],
  ['Assiut University', '2', '0.63735', '100'],
  ['Athens University of Economics & Business', '1', '0.4411', '100'],
  ['Atilim University', '1', '0.5048', '0'],
  ['Auburn University', '23', '0.460169565', '4.347826087'],
  ['Auckland University of Technology', '2', '0.83415', '50'],
  ['Augsburg University', '2', '0.5947', '0'],
  ['Australian Defense Force Academy', '12', '1.269775', '50'],
  ['Australian National University', '12', '1.748483333', '50'],
  ['Autonomous University of Barcelona', '5', '0.99546', '60'],
  ['Autonomous University of Madrid', '1', '1.2639', '0'],
  ['Avrasya University', '1', '0.306', '0'],
  ['Babes Bolyai University from Cluj', '2', '0.72025', '100'],
  ['Babol Noshirvani University of Technology',
   '13',
   '5.050615385',
   '15.38461538'],
  ['Baikal State University', '2', '0.25665', '0'],
  ['Balikesir University', '1', '0', '0'],
  ['Ball State University', '1', '1.0096', '100'],
  ['Baltic State Technical University Voenmeh', '5', '2.4073', '40'],
  ['Banaras Hindu University', '1', '0.1015', '0'],
  ['Bangalore University', '4', '0.526325', '50'],
  ['Bangkok University', '1', '0.2091', '100'],
  ['Bangladesh University Engineering & Technology',
   '3',
   '0.726366667',
   '100'],
  ['Bashkir State University', '1', '0.6617', '100'],
  ['Bauman Moscow State Technical University',
   '17',
   '0.172194118',
   '5.882352941'],
  ['Baylor College of Medicine', '1', '0', '100'],
  ['Baylor University', '10', '0.46101', '40'],
  ['Beihang University', '920', '1.337234674', '17.06521739'],
  ['Beijing Forestry University', '2', '0', '0'],
  ['Beijing Information Science & Technology University',
   '3',
   '0.230933333',
   '0'],
  ['Beijing Institute of Graphic Communication', '1', '0', '0'],
  ['Beijing Institute of Petrochemical Technology', '3', '0.3857', '0'],
  ['Beijing Institute of Technology', '261', '1.202182759', '17.62452107'],
  ['Beijing Jiaotong University', '4', '1.051025', '0'],
  ['Beijing Normal University', '4', '0.31545', '25'],
  ['Beijing Technology & Business University', '2', '1.5492', '0'],
  ['Beijing Union University', '1', '1.1122', '0'],
  ['Beijing University of Posts & Telecommunications',
   '7',
   '0.581557143',
   '0'],
  ['Beijing University of Technology', '16', '1.03184375', '25'],
  ['Belarusian State University of Informatics & Radioelectronics',
   '1',
   '0.2206',
   '100'],
  ['Ben Gurion University', '9', '0.706955556', '77.77777778'],
  ['Benha University', '1', '2.2245', '100'],
  ['Beykent University', '2', '0.43105', '50'],
  ['Bezmialem Vakif University', '1', '1.8359', '100'],
  ['Bharath Institute of Higher Education & Research', '5', '0.0355', '0'],
  ['Bialystok University of Technology', '3', '1.249866667', '0'],
  ['Bilecik Seyh Edebali University', '1', '1.0096', '0'],
  ['Binzhou University', '2', '1.02865', '0'],
  ['Birkbeck University London', '1', '1.2428', '100'],
  ['Birla Institute of Technology and Science Pilani (BITS Pilani)',
   '2',
   '0.2663',
   '50'],
  ['Birla Institute of Technology Mesra', '7', '0.524557143', '28.57142857'],
  ['Birmingham City University', '2', '0.0605', '100'],
  ['Bogazici University', '3', '0.695533333', '0'],
  ['Bohai University', '6', '2.612883333', '66.66666667'],
  ['Boston College', '2', '0.66955', '50'],
  ['Boston University', '9', '0.997166667', '11.11111111'],
  ['Brandenburg University of Technology Cottbus', '5', '0.52312', '20'],
  ['Braunschweig University of Technology',
   '44',
   '0.825159091',
   '31.81818182'],
  ['Brigham Young University', '19', '0.719626316', '0'],
  ['Brno University of Technology', '7', '0.418857143', '71.42857143'],
  ['Brock University', '2', '0.8224', '100'],
  ['Brown University', '6', '0.972016667', '33.33333333'],
  ['Brunel University', '11', '1.134409091', '36.36363636'],
  ['Bucknell University', '1', '1.5979', '0'],
  ['Budapest University of Technology & Economics',
   '7',
   '0.989228571',
   '28.57142857'],
  ['Bulent Ecevit University', '3', '1.1717', '100'],
  ['Bulgarian Academy of Sciences', '1', '0.2343', '100'],
  ['Bundeswehr University Munich', '13', '1.105', '53.84615385'],
  ['Cairo University', '5', '0.5416', '40'],
  ['California Institute of Technology', '193', '1.230839378', '17.61658031'],
  ['California Polytechnic State University San Luis Obispo',
   '8',
   '0.5427',
   '62.5'],
  ['California State Polytechnic University Pomona', '2', '0.38835', '0'],
  ['California State University Fullerton', '1', '0.9061', '0'],
  ['California State University Long Beach',
   '6',
   '0.517316667',
   '16.66666667'],
  ['California State University Los Angeles', '3', '1.6949', '0'],
  ['California State University Northridge',
   '7',
   '0.873385714',
   '14.28571429'],
  ['California State University Sacramento', '1', '0.1793', '0'],
  ['California State University San Bernardino', '1', '0.3814', '100'],
  ['Cardiff University', '14', '0.384807143', '92.85714286'],
  ['Carl von Ossietzky Universitat Oldenburg', '1', '0.4358', '100'],
  ['Carleton University', '21', '0.874119048', '28.57142857'],
  ['Carnegie Mellon University', '8', '0.4205625', '37.5'],
  ['Case Western Reserve University', '14', '1.381164286', '21.42857143'],
  ['Catholic Kwandong University', '7', '0.726757143', '100'],
  ['Catholic University of America', '5', '0.55496', '20'],
  ['Celal Bayar University', '1', '2.1306', '100'],
  ['Central China Normal University', '1', '4.1827', '0'],
  ['Central Ohio Technical College', '4', '0.0359', '75'],
  ['Central South University', '18', '1.179988889', '27.77777778'],
  ['Central University of Rajasthan (CURAJ)', '1', '0', '100'],
  ['CentraleSupelec', '15', '1.20668', '66.66666667'],
  ['Centre Universitaire Ain Temouchent', '1', '0.5561', '100'],
  ['Chalmers University of Technology', '20', '0.696955', '60'],
  ["Chang'an University", '5', '0.99892', '40'],
  ['Changchun University of Science & Technology', '1', '0.5417', '0'],
  ['Changchun University of Technology', '1', '0.2206', '0'],
  ['Changsha University of Science & Technology', '4', '1.4102', '50'],
  ['Changshu Institute of Technology', '1', '1.1122', '0'],
  ['Changzhou Institute of Technology', '1', '1.224', '0'],
  ['Changzhou University', '2', '1.2524', '0'],
  ['Charite Medical University of Berlin', '2', '0.38835', '100'],
  ['Charles University Prague', '6', '0.91095', '83.33333333'],
  ['Chaudhary Charan Singh University', '1', '0', '0'],
  ['Cheongju University', '2', '0.459', '50'],
  ['Chiba Institute of Technology', '2', '2.06055', '0'],
  ['Chiba University', '1', '1.1122', '100'],
  ['China Agricultural University', '4', '1.36385', '50'],
  ['China Jiliang University', '1', '2.4262', '0'],
  ['China University of Geosciences - Beijing', '1', '6.1173', '0'],
  ['China University of Geosciences (Wuhan)', '4', '0.785625', '75'],
  ['China University of Mining and Technology', '3', '1.4915', '33.33333333'],
  ['China University of Mining and Technology, Beijing', '1', '2.1419', '0'],
  ['China University of Petroleum - Eastern China', '1', '0', '0'],
  ['Chinese University of Hong Kong', '2', '1.101', '0'],
  ['Chonbuk National University', '10', '1.03351', '40'],
  ['Chongqing University', '25', '0.986828', '12'],
  ['Chongqing University of Posts & Telecommunications', '4', '1.8641', '50'],
  ['Chosun University', '36', '0.511480556', '11.11111111'],
  ['Chubu University', '5', '0.28696', '60'],
  ['Chukyo University', '1', '0', '100'],
  ['Chulalongkorn University', '1', '16.8669', '0'],
  ['Chung Ang University', '1', '0', '0'],
  ['Chung Hua University', '1', '0.2906', '0'],
  ['Chungbuk National University', '9', '0.318233333', '33.33333333'],
  ['Chungnam National University', '30', '0.552216667', '23.33333333'],
  ['Chung-Shan Institute of Science & Technology', '2', '1.10545', '0'],
  ['Chuo University', '2', '1.2655', '50'],
  ['City College of New York (CUNY)', '5', '0.25158', '60'],
  ['City University London', '5', '2.00554', '60'],
  ['City University of Hong Kong', '11', '1.330909091', '18.18181818'],
  ['Civil Aviation University of China', '27', '0.456844444', '11.11111111'],
  ['Clarkson University', '15', '0.741393333', '73.33333333'],
  ['Clemson University', '8', '0.6623625', '37.5'],
  ['Cleveland State University', '3', '1.9183', '66.66666667'],
  ['CNRS - National Institute for Mathematical Sciences (INSMI)',
   '1',
   '0.8877',
   '100'],
  ['College of Engineering Pune', '5', '0.34172', '20'],
  ['College of Engineering, Trivandrum', '6', '0.568066667', '16.66666667'],
  ['College of New Jersey', '1', '0.6041', '0'],
  ['Colorado School of Mines', '3', '0.419266667', '33.33333333'],
  ['Colorado State University', '11', '2.058627273', '36.36363636'],
  ['Columbia University', '9', '0.625', '22.22222222'],
  ['Comando-Geral de Tecnologia Aeroespacial (CTA)',
   '35',
   '0.678208571',
   '8.571428571'],
  ['Comillas Pontifical University', '2', '1.2131', '100'],
  ['Complutense University of Madrid', '10', '0.77595', '60'],
  ['COMSATS Institute of Information Technology (CIIT)',
   '15',
   '1.050546667',
   '80'],
  ['Concordia University - Canada', '28', '1.729510714', '50'],
  ['Consejo Nacional de Investigaciones Cientificas y Tecnicas (CONICET)',
   '3',
   '0.780766667',
   '33.33333333'],
  ['Conservatoire National Arts & Metiers (CNAM)', '3', '1.0692', '100'],
  ['Cornell University', '36', '1.168080556', '8.333333333'],
  ['Council of Scientific & Industrial Research (CSIR) - India',
   '41',
   '0.558853659',
   '21.95121951'],
  ['Coventry University', '6', '0.294066667', '33.33333333'],
  ['Cracow University of Technology', '1', '2.4479', '0'],
  ['Cranfield University', '174', '0.653532759', '39.65517241'],
  ['CSIR Fourth Paradigm Institute (CSIR 4PI)', '1', '0.5378', '0'],
  ['Cukurova University', '2', '0.66575', '0'],
  ['Cumhuriyet University', '1', '0.1453', '0'],
  ['Curtin University', '11', '0.767518182', '72.72727273'],
  ['Czech Technical University Prague', '11', '1.151018182', '72.72727273'],
  ['Daegu Gyeongbuk Institute of Science & Technology', '2', '0.9852', '0'],
  ['Dalhousie University', '2', '0.53575', '0'],
  ['Dalian Jiaotong University', '2', '0.10365', '0'],
  ['Dalian Maritime University', '7', '1.395742857', '0'],
  ['Dalian Polytechnic University', '1', '1.1122', '0'],
  ['Dalian University', '1', '0.9196', '0'],
  ['Dalian University of Technology', '63', '1.615471429', '7.936507937'],
  ['Darmstadt University of Technology', '17', '1.516152941', '47.05882353'],
  ['Dartmouth College', '5', '0.08484', '0'],
  ['De Montfort University', '3', '0.540666667', '0'],
  ['Deakin University', '5', '1.91506', '100'],
  ['Defence Institute of Advanced Technology (DIAT)',
   '21',
   '0.492461905',
   '0'],
  ['Delft University of Technology', '239', '1.0703159', '44.35146444'],
  ['Democritus University of Thrace', '4', '1.08055', '100'],
  ['Dogus University', '2', '1.05565', '100'],
  ['Dokuz Eylul University', '1', '0.612', '100'],
  ['Donghua University', '2', '1.07095', '50'],
  ['Dortmund University of Technology', '3', '0.6349', '0'],
  ['Doshisha University', '1', '0', '100'],
  ['Dresden University of Technology', '5', '0.35602', '60'],
  ['Drexel University', '3', '1.248766667', '33.33333333'],
  ['Duke University', '35', '0.74558', '34.28571429'],
  ['Durham University', '11', '0.752490909', '63.63636364'],
  ['Duy Tan University', '2', '2.42', '100'],
  ['East Carolina University', '5', '0.23074', '40'],
  ['East China Jiaotong University', '2', '0.612', '0'],
  ['East China Normal University', '1', '1.7617', '100'],
  ['East China University of Science & Technology', '3', '1.499633333', '0'],
  ['Eastern Connecticut State University', '1', '0', '0'],
  ['Eastern Mediterranean University', '1', '0', '0'],
  ['Eberhard Karls University of Tubingen', '7', '0.462614286', '42.85714286'],
  ['Ecole Centrale de Lyon', '34', '1.098308824', '38.23529412'],
  ['Ecole Centrale de Nantes', '1', '0', '100'],
  ['Ecole de Technologie Superieure - Canada', '44', '0.784', '13.63636364'],
  ['Ecole Military Polytechnic', '4', '0.5418', '75'],
  ["Ecole Nationale de l'Aviation Civile (ENAC)",
   '12',
   '0.570075',
   '66.66666667'],
  ['Ecole Nationale Polytechnique - Algeria', '1', '0.1007', '100'],
  ["Ecole Nationale Superieure d'Arts et Metiers (Arts et Metiers ParisTech)",
   '4',
   '1.2667',
   '25'],
  ["Ecole Nationale Superieure de Mecanique et d'Aerotechnique (ISAE-ENSMA)",
   '6',
   '0.971133333',
   '33.33333333'],
  ["Ecole Nationale Superieure des Mines d'Albi-Carmaux",
   '6',
   '0.544966667',
   '16.66666667'],
  ['Ecole Normale Superieure de Lyon (ENS LYON)', '1', '1.4538', '0'],
  ['Ecole Normale Superieure Paris-Saclay', '5', '0.60008', '60'],
  ['Ecole Polytechnique', '3', '2.182466667', '100'],
  ['Ecole Polytechnique Federale de Lausanne',
   '21',
   '1.053633333',
   '66.66666667'],
  ['Ecole Superieure de Physique et de Chimie Industrielles de la Ville de Paris (ESPCI)',
   '11',
   '0.245890909',
   '36.36363636'],
  ['Ehime University', '3', '0.299633333', '33.33333333'],
  ['Eindhoven University of Technology', '6', '0.16855', '83.33333333'],
  ['Embry-Riddle Aeronautical University', '90', '0.399121111', '6.666666667'],
  ['Emirates Aviation College', '1', '0', '0'],
  ['ENSTA Bretagne', '2', '1.3652', '0'],
  ['ENSTA ParisTech', '1', '0.6617', '0'],
  ['Eotvos Lorand University', '5', '0.68388', '100'],
  ['Erciyes University', '13', '0.897569231', '46.15384615'],
  ['Ernst Moritz Arndt Universitat Greifswald', '1', '0', '0'],
  ['Escuela Politecnica Nacional Ecuador', '2', '0', '100'],
  ['Eskisehir Osmangazi University', '3', '0.185366667', '0'],
  ['Estonian University of Life Sciences', '2', '2.13055', '50'],
  ['ETH Zurich', '24', '1.499679167', '79.16666667'],
  ['European Southern Observatory', '2', '1.9453', '100'],
  ['Faculdade de Tecnologia Senai Cimatec', '1', '1.1122', '0'],
  ['Fairfield University', '1', '0', '0'],
  ['Fayoum University', '2', '0.2349', '100'],
  ['Feng Chia University', '1', '0', '0'],
  ['Ferdowsi University Mashhad', '19', '1.452547368', '10.52631579'],
  ['Florida A&M University', '6', '1.071683333', '16.66666667'],
  ['Florida Atlantic University', '16', '0.90548125', '25'],
  ['Florida Gulf Coast University', '1', '0', '0'],
  ['Florida Institute of Technology', '21', '0.73322381', '61.9047619'],
  ['Florida International University', '5', '2.43448', '40'],
  ['Florida State University', '20', '1.070095', '5'],
  ['Free University of Berlin', '2', '0.38835', '100'],
  ['Free University of Bozen-Bolzano', '1', '1.1122', '0'],
  ['Fu Jen Catholic University', '2', '0.61975', '50'],
  ['Fudan University', '21', '0.632319048', '9.523809524'],
  ['Fujian University of Technology', '1', '0.4598', '0'],
  ['Fuzhou University', '3', '1.990433333', '0'],
  ['Gazi University', '2', '0.43185', '0'],
  ['Gaziantep University', '4', '0.302225', '50'],
  ['Gdansk University of Technology', '4', '1.778475', '50'],
  ['Gebze Technical University', '7', '0.433271429', '71.42857143'],
  ['George Mason University', '9', '1.157933333', '22.22222222'],
  ['George Washington University', '30', '1.121663333', '26.66666667'],
  ['Georgia Institute of Technology', '284', '0.879727465', '11.97183099'],
  ['Georgia State University', '1', '0.4389', '0'],
  ['GH Asachi Technical University', '3', '1.664133333', '66.66666667'],
  ['Ghent University', '3', '0.828533333', '66.66666667'],
  ['Glyndwr University', '1', '0', '100'],
  ['Graduate University for Advanced Studies - Japan',
   '9',
   '1.183433333',
   '44.44444444'],
  ['Graz University of Technology', '8', '0.441475', '37.5'],
  ['Griffith University', '2', '5.04885', '50'],
  ['Guangdong Polytech Normal University', '1', '1.1122', '0'],
  ['Guangxi University of Science & Technology', '1', '0.918', '0'],
  ['Guilin University of Electronic Technology', '1', '1.1028', '0'],
  ['Gumushane University', '1', '0', '0'],
  ['Gunma University', '4', '0.1883', '25'],
  ['Gwangju Institute of Science & Technology',
   '6',
   '0.448916667',
   '16.66666667'],
  ['Gyeongsang National University', '18', '1.006222222', '22.22222222'],
  ['Hacettepe University', '3', '0.4207', '0'],
  ['Hainan University', '1', '0.5561', '0'],
  ['Hallym University', '1', '0.1174', '0'],
  ['Hamburg University of Technology', '6', '1.13665', '16.66666667'],
  ['Hamilton College', '1', '1.4528', '100'],
  ['Hampton University', '1', '0.7047', '0'],
  ['Hanbat National University', '6', '0.710583333', '0'],
  ['Hangzhou Dianzi University', '10', '0.79643', '50'],
  ['Hanoi University of Science & Technology', '3', '0.528833333', '100'],
  ['Hanyang University', '26', '0.587103846', '19.23076923'],
  ['Harbin Engineering University', '31', '1.354664516', '25.80645161'],
  ['Harbin Institute of Technology', '421', '1.654424466', '18.76484561'],
  ['Harbin University of Commerce', '3', '0.9035', '33.33333333'],
  ['Harbin University of Science & Technology',
   '3',
   '1.935266667',
   '33.33333333'],
  ['Harokopio University Athens', '1', '0.3352', '100'],
  ['Harvard University', '12', '4.863875', '50'],
  ['Hebei University of Engineering', '2', '0', '100'],
  ['Hebrew University of Jerusalem', '4', '0.423925', '50'],
  ['HEC Montreal', '1', '0', '0'],

In [10]:
def judge(lis,compare_numb,counter,cnci):
    '''统计'''
    if int(lis[1])>=compare_numb:
        counter[0]=str(int(counter[0])+1)
        cnci.append(lis[2])
    return counter,cnci

In [10]:
qwq=['1','3','4','5']

In [11]:
qwq.count

In [12]:
mean_cnci(qwq)

3.25

In [8]:
def mean_cnci(cnci):
    total=0
    for ite in cnci:
        total=float(ite)+total
        mean=total/len(cnci)
    return mean

In [23]:
def savedata(item,couter,cnci,subject):
    subject.append(couter[0])
    subject.append(max([float(x) for x in cnci]))
    flag1=0
    for item_4 in item[1]:
        if max(cnci)!='0' and (str(subject[-1]) in item_4):
            subject.append(item_4[0])
            flag1=1
            break
    if flag1== 0:
        subject.append('0')
    return subject,counter,cnci

In [24]:
result=[]
result.append(['Subject','counter','counter_25','cnci_25_max','Institute_max','counter_50','cnci_50_max','Institute_max',\
              'counter_100','cnci_100_max','Institute_max','counter_125','cnci_125_max','Institute_max','counter_150','cnci_150_max','Institute_max',\
              'counter_200','cnci_200_max','Institute_max','counter_250','cnci_250_max','Institute_max','counter_300','cnci_300_max','Institute_max',\
              'counter_400','cnci_400_max','Institute_max','counter_500','cnci_500_max','Institute_max','counter_750','cnci_750_max','Institute_max',\
              'counter_1000','cnci_1000_max','Institute_max',])
for item_3 in final_lis:
    subject=[]
    counter_25=['0']
    counter_50=['0']
    counter_100=['0']
    counter_125=['0']
    counter_150=['0']
    counter_200=['0']
    counter_250=['0']
    counter_300=['0']
    counter_400=['0']
    counter_500=['0']
    counter_750=['0']
    counter_1000=['0']
        
    cnci_25=['0']
    cnci_50=['0']
    cnci_100=['0']
    cnci_125=['0']
    cnci_150=['0']
    cnci_200=['0']
    cnci_250=['0']
    cnci_300=['0']
    cnci_400=['0']
    cnci_500=['0']
    cnci_750=['0']
    cnci_1000=['0']
    subject.append(item_3[0])
    subject.append(len(item_3[1]))
    
    for item_4 in item_3[1]:
        for item in [25,50,100,125,150,200,250,300,400,500,750,1000]:
            cnci = globals()['cnci_%s'%item]
            counter=globals()['counter_%s'%item]
            counter,cnci=judge(item_4,item,counter,cnci)
            
    for item in [25,50,100,125,150,200,250,300,400,500,750,1000]:
        cnci = globals()['cnci_%s'%item]#
        counter=globals()['counter_%s'%item]#   
        subject,counter,cnci=savedata(item_3,counter,cnci,subject)
            
    result.append(subject)

In [25]:
len(result[0])

38

In [26]:
len(result[1])

38

In [27]:
#################################### 保存文件 ###############################
result_latest=pd.DataFrame(np.array(result))#将pd.DataFrame(np.array(myarray))写入list
result_latest.to_csv("C:/Users/rk/Desktop/fawenyuzhi888.csv",index=False,encoding='GB18030')
result_latest

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
0,Subject,counter,counter_25,cnci_25_max,Institute_max,counter_50,cnci_50_max,Institute_max,counter_100,cnci_100_max,...,Institute_max,counter_500,cnci_500_max,Institute_max,counter_750,cnci_750_max,Institute_max,counter_1000,cnci_1000_max,Institute_max
1,Aerospace Engineering,1532,170,3.130375758,Princeton University,80,1.950663462,York University - Canada,28,1.939482,...,Harbin Institute of Technology,1,1.337234674,Beihang University,1,1.337234674,Beihang University,0,0.0,0
2,Agricultural Economics,1176,52,2.097242373,University of Illinois Urbana-Champaign,15,2.097242373,University of Illinois Urbana-Champaign,4,1.651577311,...,0,0,0.0,0,0,0.0,0,0,0.0,0
3,Agricultural Engineering,2340,287,3.415355556,University of Massachusetts Amherst,117,2.092468085,University of Technology Sydney,32,1.946247651,...,0,0,0.0,0,0,0.0,0,0,0.0,0
4,Agricultural Sciences,4351,1932,3.182104386,Princeton University,1352,3.182104386,Princeton University,908,3.182104386,...,University of Cambridge,187,1.964083296,University of California Berkeley,99,1.964083296,University of California Berkeley,60,1.684198009,Wageningen University & Research
5,Atmospheric Science,3174,732,5.28378,Universidade da Beira Interior,444,3.340315942,Montana State University Bozeman,242,2.946729907,...,ETH Zurich,30,2.346135751,ETH Zurich,12,2.346135751,ETH Zurich,4,1.927935455,California Institute of Technology
6,Automation & Control,3197,801,5.915569444,Griffith University,462,5.757797647,Liaoning University of Technology,214,5.318996703,...,City University of Hong Kong,12,2.700051724,Southeast University - China,6,2.335073474,Harbin Institute of Technology,2,2.335073474,Harbin Institute of Technology
7,Biological Sciences,5120,3139,11.12705532,Danube University Krems,2521,6.452532381,Harokopio University Athens,1931,6.452532381,...,Massachusetts Institute of Technology (MIT),781,3.703053066,Massachusetts Institute of Technology (MIT),587,3.703053066,Massachusetts Institute of Technology (MIT),449,3.703053066,Massachusetts Institute of Technology (MIT)
8,Biomedical Engineering,3461,932,3.675296429,Ecole Normale Superieure (ENS),600,2.783696296,China Pharmaceutical University,347,2.347423967,...,Massachusetts Institute of Technology (MIT),15,2.173657371,Massachusetts Institute of Technology (MIT),3,1.66270934,Harvard University,1,1.66270934,Harvard University
9,Biotechnology,4144,1497,5.713271739,Johns Hopkins Bloomberg School of Public Health,970,5.713271739,Johns Hopkins Bloomberg School of Public Health,558,5.227403943,...,Massachusetts Institute of Technology (MIT),42,5.227403943,Massachusetts Institute of Technology (MIT),7,4.392609472,Harvard University,4,4.392609472,Harvard University
10,Business Administration,2967,822,6.19449,Otto von Guericke University,493,4.156294118,University of Hawaii Manoa,229,2.930523077,...,Harvard University,1,1.500031993,Harvard University,0,0.0,0,0,0.0,0
11,Chemical Engineering,3879,1439,3.494803509,Chongqing Technology & Business University,940,3.494803509,Chongqing Technology & Business University,551,3.485484076,...,Nanyang Technological University,60,2.455116154,Nanyang Technological University,22,1.966523235,National University of Singapore,10,1.605370468,South China University of Technology
12,Chemistry,5009,3116,3.378620588,Nanyang Polytechnic,2598,2.830664407,Education University of Hong Kong (EdUHK),2026,2.830664407,...,Kent State University,787,2.491471959,Stanford University,552,2.491471959,Stanford University,396,2.491471959,Stanford University
13,Civil Engineering,3425,964,11.691655,Sohag University,628,7.966403571,University Djillali Liabes Sidi Bel Abbes,351,7.966403571,...,Hong Kong University of Science & Technology,32,1.490899238,University of California Berkeley,10,1.391222476,Hong Kong Polytechnic University,3,1.369343099,Tsinghua University
14,Clinical Medicine,4689,2574,46.116888,Birzeit University,2061,46.116888,Birzeit University,1578,22.24408981,...,Auckland University of Technology,784,5.65805169,Addis Ababa University,635,4.035903759,Johns Hopkins Oncology Center,531,4.035903759,Johns Hopkins Oncology Center
15,Communication,2071,357,4.475678788,University Hohenheim,191,3.151765169,Stanford University,74,2.985405147,...,0,0,0.0,0,0,0.0,0,0,0.0,0
16,Computer Science & Engineering,4565,2048,5.767938462,International School for Advanced Studies,1470,5.484278788,Liaoning University of Technology,988,5.484278788,...,Nanjing University of Information Science & Te...,183,3.556098994,Nanjing University of Information Science & Te...,103,2.495561034,King Abdulaziz University,50,2.495561034,King Abdulaziz University
17,Dentistry & Oral Sciences,2074,559,2.6428,University of Maryland Baltimore County,372,2.539948387,Laval University,228,2.106383274,...,University of Washington Seattle,12,1.769603737,University of Bern,4,1.178047952,Harvard University,2,1.083540192,Universidade Estadual Paulista
18,Earth Sciences,3901,1427,5.480416901,University Hohenheim,1037,5.480416901,University Hohenheim,709,3.340219394,...,University of California Irvine,175,2.362922987,Princeton University,86,2.351739428,Universite de Versailles Saint-Quentin-En-Yvel...,47,2.106414126,University of Washington Seattle
19,Ecology,3701,1127,3.677534091,Universidad Nacional de San Antonio Abad del C...,765,3.424143333,City College of New York (CUNY),508,2.832976684,...,University of Leeds,84,2.304230653,Stanford University,35,2.130828094,Imperial College London,20,2.103399664,University of California Berkeley
20,Economics,3376,1136,5.598155556,New Mexico Institute of Mining Technology,791,3.379353439,Dartmouth College,479,3.379353439,...,Princeton University,45,2.946634594,Princeton University,15,2.854242737,Massachusetts Institute of Technology (MIT),5,2.520190126,Harvard University
21,Education,3687,1023,3.239070588,University of Maine Orono,672,3.239070588,University of Maine Orono,378,3.133507983,...,Vanderbilt University,40,1.84771644,Vanderbilt University,9,1.544566584,Michigan State University,2,1.250695124,University of Toronto
22,Electrical & Electronic Engineering,4220,1859,6.999354651,Liaoning University of Technology,1362,6.999354651,Liaoning University of Technology,889,5.244737727,...,New York University,189,3.031248511,Nanjing University of Information Science & Te...,109,2.812006193,University of Texas Austin,60,2.808809114,Aalborg University
23,Energy Science & Engineering,4126,1565,3.236845161,Chongqing Technology & Business University,1068,2.939057143,National University of Ireland (NUI) Galway,629,2.825443678,...,Ecole Polytechnique Federale de Lausanne,104,2.769646308,Ecole Polytechnique Federale de Lausanne,46,2.621485092,Nanyang Technological University,19,1.731061469,South China University of Technology
24,Environmental Science & Engineering,4785,2216,3.406640625,Nanyang Normal College,1579,3.267972581,Auckland University of Technology,1027,2.828912903,...,Ecole Polytechnique Federale de Lausanne,200,2.659193482,Ecole Polytechnique Federale de Lausanne,103,2.258311716,Stanford University,52,2.258311716,Stanford University
25,Finance,2116,481,5.299204878,Dartmouth College,252,3.983347549,University of Chicago,96,3.983347549,...,0,0,0.0,0,0,0.0,0,0,0.0,0
26,Food Science & Technology,3848,1188,3.16672,Instituto Federal do Rio de Janeiro (IFRJ),714,2.216272146,University of Massachusetts Amherst,392,2.216272146,...,University of Massachusetts Amherst,24,1.822763062,South China University of Technology,11,1.822763062,South China University of Technology,4,1.330008919,China Agricultural University
27,Geography,3336,866,3.864839394,University of Denver,568,3.864839394,University of Denver,307,2.363906211,...,Wageningen University & Research,9,2.035294167,Utrecht University,1,1.698675591,University of Oxford,0,0.0,0
28,Geological Engineering,1711,269,2.344463333,University of Salerno,138,2.344463333,University of Salerno,53,2.081297059,...,Tongji University,0,0.0,0,0,0.0,0,0,0.0,0
29,Hospitality & Tourism Management,2018,300,3.021651724,Harbin Institute of Technology,117,2.691678652,University of Nevada Las Vegas,41,2.674308475,...,Hong Kong Polytechnic University,0,0.0,0,0,0.0,0,0,0.0,0
30,Human Biological Sciences,4616,2168,3.603935885,Johns Hopkins Oncology Center,1644,3.603935885,Johns Hopkins Oncology Center,1205,3.603935885,...,Massachusetts Institute of Technology (MIT),431,3.003217686,Massachusetts Institute of Technology (MIT),314,3.003217686,Massachusetts Institute of Technology (MIT),231,3.003217686,Massachusetts Institute of Technology (MIT)
31,Instruments Science & Technology,3718,1068,8.388592593,University of Cyprus,667,5.827253125,Bogazici University,346,3.678817483,...,ETH Zurich,13,1.641369098,Harbin Institute of Technology,3,1.641369098,Harbin Institute of Technology,1,1.113582951,Tsinghua University
32,Law,2156,514,4.222895,Carnegie Mellon University,300,2.862083333,Iowa State University,165,2.862083333,...,Yale University,7,2.808960036,Yale University,1,2.412958176,Harvard University,0,0.0,0
33,Library & Information Science,2596,372,4.523792,Ryerson University,167,2.969271698,University of Quebec Montreal,51,2.727388321,...,0,0,0.0,0,0,0.0,0,0,0.0,0
34,Management,3700,1239,3.260932203,University of Denver,821,3.260932203,University of Denver,470,2.535825714,...,Michigan State University,18,1.8265355,Arizona State University,3,1.671379918,Hong Kong Polytechnic University,0,0.0,0
35,Marine/Ocean Engineering,1290,126,2.572707143,Utrecht University,58,2.45567451,Universidad de Cantabria,16,1.308696396,...,Shanghai Jiao Tong University,0,0.0,0,0,0.0,0,0,0.0,0
36,Materials Science & Engineering,4714,2583,4.034413208,Education University of Hong Kong (EdUHK),2069,4.034413208,Education University of Hong Kong (EdUHK),1538,2.715369036,...,Drexel University,466,2.476509845,Drexel University,297,2.428196145,Stanford University,207,2.428196145,Stanford University
37,Mathematics,4045,1900,6.548206965,Shandong University of Science & Technology,1397,6.548206965,Shandong University of Science & Technology,920,6.548206965,...,China University of Mining and Technology,129,2.002511924,New York University,44,1.944880197,Stanford University,9,1.848998332,King Abdulaziz University
38,Mechanical Engineering,3646,1193,7.756491398,University Djillali Liabes Sidi Bel Abbes,758,7.756491398,University Djillali Liabes Sidi Bel Abbes,437,4.520608955,...,University of Science & Technology of China,45,1.532920714,University of Science & Technology of China,18,1.350220296,Islamic Azad University,12,1.350220296,Islamic Azad University
39,Medical Technology,3332,937,5.874825926,Northeast Ohio Medical University (NEOMED),665,3.164483529,Victor Babes University of Medicine & Pharmacy...,419,2.818098522,...,Radboud University Nijmegen,79,2.016818626,Radboud University Nijmegen,38,2.016818626,Radboud University Nijmegen,18,1.722327198,University College London
40,Metallurgical Engineering,3120,822,3.364009259,Edith Cowan University,503,3.364009259,Edith Cowan University,242,2.433032704,...,Huazhong University of Science & Technology,23,1.034618063,Huazhong University of Science & Technology,10,0.913623409,Chongqing University,7,0.879061341,Shanghai Jiao Tong University
41,Mining & Mineral Engineering,1734,160,2.531109375,University of Texas Austin,68,2.452917391,Peking University,17,1.789079839,...,University of Science & Technology Beijing,0,0.0,0,0,0.0,0,0,0.0,0
42,Nanoscience & Nanotechnology,3831,1446,3.493583051,Universitat Jaume I,998,3.493583051,Universitat Jaume I,632,3.493583051,...,Rice University,108,2.662012262,Rice University,61,2.549385556,Stanford University,36,2.549385556,Stanford University
43,Nursing,2245,556,2.728126923,Dublin City University,325,2.234011475,University of Oxford,145,1.812295,...,University of Pennsylvania,2,1.305292832,University of Pennsylvania,1,0.505146228,Universidade de Sao Paulo,0,0.0,0
44,Oceanography,2392,442,2.484565217,University of Vienna,250,2.28658,University of California Irvine,132,2.27142013,...,University of Southampton,4,1.88132381,University of Washington Seattle,1,0.609577344,Ocean University of China,1,0.609577344,Ocean University of China
45,Pharmacy & Pharmaceutical Sciences,4404,1947,3.691692251,University of Dundee,1432,3.691692251,University of Dundee,931,3.691692251,...,University of Nottingham,170,1.71978837,University of Florence,76,1.71978837,University of Florence,32,1.71978837,University of Florence
46,Physics,4917,2904,34.55447419,Hillsdale College,2381,23.43998289,Whitman College,1855,18.1122767,...,University of Urbino,803,4.924725811,Gran Sasso Scientific Institute,582,4.416704883,Syracuse University,458,3.764502504,Cardiff University
47,Political Sciences,2528,668,4.218279412,Drexel University,414,3.374450584,Stanford University,220,3.374450584,...,Stanford University,12,3.374450584,Stanford University,3,2.5852971,Harvard University,2,2.5852971,Harvard University
48,Psychology,3895,1462,8.263013793,Stockholm School of Economics,1085,4.164359016,Kutztown University - Pennsylvania,755,2.85427,...,Massachusetts Institute of Technology (MIT),218,1.893066032,University of Virginia,118,1.893066032,University of Virginia,82,1.854025408,Stanford University
49,Public Administration,1752,208,3.7346,University of Bern,82,3.095755,University of Georgia,17,3.095755,...,0,0,0.0,0,0,0.0,0,0,0.0,0
50,Public Health,4559,1971,39.2422093,Universidad de Cartagena,1461,31.68659123,National Research University - Higher School o...,991,16.32000088,...,Aga Khan University,310,3.742466281,Korea University,205,3.416233595,University of California Irvine,152,2.934965249,Ruprecht Karls University Heidelberg
51,Remote Sensing,2253,369,4.97745,Hunan University,172,3.480283871,University of Iceland,57,3.480283871,...,University of Maryland College Park,2,1.440321658,Wuhan University,1,1.440321658,Wuhan University,1,1.440321658,Wuhan University
52,Sociology,2497,508,3.56045625,Boston College,288,3.56045625,Boston College,126,3.037684028,...,University of Oxford,0,0.0,0,0,0.0,0,0,0.0,0
53,Sport Sciences,2537,694,4.6966,University of Pretoria,443,3.677343902,Medical College of Wisconsin,208,3.034513876,...,University of North Carolina Chapel Hill,4,1.866532246,University of Queensland,0,0.0,0,0,0.0,0
54,Statistics,3054,776,9.085784416,Karlsruhe Institute of Technology,491,9.085784416,Karlsruhe Institute of Technology,221,4.933574286,...,Columbia University,5,1.500192473,Stanford University,0,0.0,0,0,0.0,0
55,Telecommunication Engineering,3170,910,6.856162712,Pompeu Fabra University,545,6.856162712,Pompeu Fabra University,304,4.946542222,...,National University of Singapore,21,2.6486736,University of British Columbia,8,1.93678881,Nanyang Technological University,5,1.80474324,Tsinghua University
56,Transportation Science & Technology,2396,423,3.225035294,Peking University,238,3.225035294,Peking University,99,2.481748603,...,Tsinghua University,2,1.638284826,Beijing Jiaotong University,0,0.0,0,0,0.0,0
57,Veterinary Sciences,2782,593,2.42345,South China Normal University,353,1.940453846,McGill University,217,1.794352941,...,Wageningen University & Research,34,1.401825974,University of Sydney,14,1.398120039,University of London Royal Veterinary College,5,1.398120039,University of London Royal Veterinary College
58,Water Resources,3669,1022,3.708180769,University College of Southeast Norway,566,3.117084746,University of Reading,279,2.483343511,...,ETH Zurich,8,1.45411726,Delft University of Technology,1,0.923963951,Hohai University,0,0.0,0

In [111]:
#读入csv中的数据，（导入检索式）
yuzhi = []
csv_reader=csv.reader(open(r'C:\Users\rk\Desktop\yuz.csv',encoding='GB18030'))#打开文件
for row in csv_reader:
    yuzhi.append(row)#将读入的数据赋值给列表a

In [112]:
yuzhi[0]

['学科英文名', '2019论文数阈值', '论文阈值1', '论文阈值2', '论文阈值3', '论文阈值5倍']

In [113]:
del yuzhi[0]

In [114]:
yuzhi[0]

['Aerospace Engineering', '50', '25', '100', '', '250']

In [115]:
y={'25':'counter_25','50':'counter_50','100':'counter_100','125':'counter_125','150':'counter_150','200':'counter_200',\
       '300':'counter_300','250':'counter_250','400':'counter_400','500':'counter_500','750':'counter_750','1000':'counter_1000'}

In [137]:
yuzhi[0]

['Aerospace Engineering', '50', '25', '100', '', '250']

In [179]:
final_list=[]
for element in result[1:]:#逐行循环result学科
    fin=[]
    for item in yuzhi:#逐行循环学科发文阈值
        if element[0]==item[0]:#判断学科名称是否相等
            fin.extend(element[:2])
            #print(element[0])
            for ele in item:#开始循环yuzhi
                try:
                    num=y[str(ele)]
                    #print(num)
                except:
                    continue
                for it in result[0]:#开始循环result首行
                    if it==num:
                        #print(num)
                        ix=result[0].index(num)
                        ix_end=ix+3
                        fin.append(ele)
                        fin.extend(element[ix:ix_end])
                        print(element[ix:ix_end])
    final_list.append(fin)

['80', 1.950663462, 'York University - Canada']
['170', 3.130375758, 'Princeton University']
['28', 1.939482, 'University of Naples Federico II']
['7', 1.654424466, 'Harbin Institute of Technology']
['908', 3.182104386, 'Princeton University']
['1352', 3.182104386, 'Princeton University']
['705', 3.051265116, 'Columbia University']
['543', 2.524419685, 'Western Sydney University']
['187', 1.964083296, 'University of California Berkeley']
['444', 3.340315942, 'Montana State University Bozeman']
['732', 5.28378, 'Universidade da Beira Interior']
['242', 2.946729907, 'University of Montana']
['88', 2.734927324, 'University of Exeter']
['214', 5.318996703, 'Bohai University']
['462', 5.757797647, 'Liaoning University of Technology']
['126', 5.318996703, 'Bohai University']
['12', 2.700051724, 'Southeast University - China']
['1383', 5.358596089, 'Tokyo Metropolitan University']
['1596', 5.358596089, 'Tokyo Metropolitan University']
['1226', 5.358596089, 'Tokyo Metropolitan University']
['1109', 5.358596089, 'Tokyo Metropolitan University']
['449', 3.703053066, 'Massachusetts Institute of Technology (MIT)']
['347', 2.347423967, 'City University of Hong Kong']
['600', 2.783696296, 'China Pharmaceutical University']
['223', 2.175826129, 'Suzhou University']
['15', 2.173657371, 'Massachusetts Institute of Technology (MIT)']
['558', 5.227403943, 'Massachusetts Institute of Technology (MIT)']
['970', 5.713271739, 'Johns Hopkins Bloomberg School of Public Health']
['357', 5.227403943, 'Massachusetts Institute of Technology (MIT)']
['42', 5.227403943, 'Massachusetts Institute of Technology (MIT)']
['493', 4.156294118, 'University of Hawaii Manoa']
['229', 2.930523077, 'Universidade Nova de Lisboa']
['112', 2.522106787, 'Texas A&M University College Station']
['34', 2.196307973, 'Indiana University Bloomington']
['551', 3.485484076, 'University of Oxford']
['940', 3.494803509, 'Chongqing Technology & Business University']
['367', 3.485484076, 'University of Oxford']
['60', 2.455116154, 'Nanyang Technological University']
['1448', 2.553708559, 'Kent State University']
['1151', 2.553708559, 'Kent State University']
['940', 2.553708559, 'Kent State University']
['787', 2.491471959, 'Stanford University']
['396', 2.491471959, 'Stanford University']
['351', 7.966403571, 'University Djillali Liabes Sidi Bel Abbes']
['628', 7.966403571, 'University Djillali Liabes Sidi Bel Abbes']
['239', 4.60815, 'King Abdulaziz University']
['32', 1.490899238, 'University of California Berkeley']
['1178', 11.00893565, 'University of the Philippines Manila']
['1317', 12.59830191, 'Sri Ramachandra University']
['1093', 8.729352695, 'Jordan University of Science & Technology']
['1013', 8.729352695, 'Jordan University of Science & Technology']
['531', 4.035903759, 'Johns Hopkins Oncology Center']
['357', 4.475678788, 'University Hohenheim']
['191', 3.151765169, 'Stanford University']
['74', 2.985405147, 'Cornell University']
['48', 2.985405147, 'Cornell University']
['723', 5.484278788, 'Liaoning University of Technology']
['988', 5.484278788, 'Liaoning University of Technology']
['573', 3.88744867, 'McMaster University']
['103', 2.495561034, 'King Abdulaziz University']
['372', 2.539948387, 'Laval University']
['559', 2.6428, 'University of Maryland Baltimore County']
['228', 2.106383274, 'KU Leuven']
['63', 2.106383274, 'KU Leuven']
['709', 3.340219394, 'University of Waikato']
['536', 3.340219394, 'University of Waikato']
['446', 3.007104632, 'University of California Irvine']
['175', 2.362922987, 'Princeton University']
['508', 2.832976684, 'Universite de Versailles Saint-Quentin-En-Yvelines']
['765', 3.424143333, 'City College of New York (CUNY)']
['382', 2.832976684, 'Universite de Versailles Saint-Quentin-En-Yvelines']
['84', 2.304230653, 'Stanford University']
['791', 3.379353439, 'Dartmouth College']
['1136', 5.598155556, 'New Mexico Institute of Mining Technology']
['479', 3.379353439, 'Dartmouth College']
['160', 2.946634594, 'Princeton University']
['672', 3.239070588, 'University of Maine Orono']
['1023', 3.239070588, 'University of Maine Orono']
['378', 3.133507983, 'National Taiwan University of Science & Technology']
['122', 2.031730279, 'University of California San Francisco']
['633', 5.244737727, 'Victoria University']
['889', 5.244737727, 'Victoria University']
['494', 5.244737727, 'Victoria University']
['408', 3.319216547, 'Lancaster University']
['109', 2.812006193, 'University of Texas Austin']
['629', 2.825443678, 'University of Nebraska Lincoln']
['1068', 2.939057143, 'National University of Ireland (NUI) Galway']
['426', 2.825443678, 'University of Nebraska Lincoln']
['104', 2.769646308, 'Ecole Polytechnique Federale de Lausanne']
['617', 2.828912903, 'Suzhou University']
['773', 2.828912903, 'Suzhou University']
['481', 2.828912903, 'Suzhou University']
['393', 2.659193482, 'Ecole Polytechnique Federale de Lausanne']
['52', 2.258311716, 'Stanford University']
['252', 3.983347549, 'University of Chicago']
['96', 3.983347549, 'University of Chicago']
['32', 3.983347549, 'University of Chicago']
['4', 2.311131611, 'New York University']
['392', 2.216272146, 'University of Massachusetts Amherst']
['714', 2.216272146, 'University of Massachusetts Amherst']
['258', 2.216272146, 'University of Massachusetts Amherst']
['24', 1.822763062, 'South China University of Technology']
['307', 2.363906211, 'University of East Anglia']
['568', 3.864839394, 'University of Denver']
['191', 2.363906211, 'University of East Anglia']
['9', 2.035294167, 'Utrecht University']
['300', 3.021651724, 'Harbin Institute of Technology']
['117', 2.691678652, 'University of Nevada Las Vegas']
['41', 2.674308475, 'Virginia Polytechnic Institute & State University']
['25', 2.27791195, 'Bournemouth University']
['1205', 3.603935885, 'Johns Hopkins Oncology Center']
['1644', 3.603935885, 'Johns Hopkins Oncology Center']
['973', 3.603935885, 'Johns Hopkins Oncology Center']
['836', 3.603935885, 'Johns Hopkins Oncology Center']
['431', 3.003217686, 'Massachusetts Institute of Technology (MIT)']
['346', 3.678817483, 'King Abdulaziz University']
['667', 5.827253125, 'Bogazici University']
['208', 2.339700592, 'University of California San Diego']
['13', 1.641369098, 'Harbin Institute of Technology']
['300', 2.862083333, 'Iowa State University']
['514', 4.222895, 'Carnegie Mellon University']
['165', 2.862083333, 'Iowa State University']
['46', 2.808960036, 'Yale University']
['167', 2.969271698, 'University of Quebec Montreal']
['372', 4.523792, 'Ryerson University']
['51', 2.727388321, 'University of Wolverhampton']
['1', 1.624527953, 'Harvard University']
['821', 3.260932203, 'University of Denver']
['470', 2.535825714, 'Rice University']
['284', 2.484022174, 'IU Kelley School of Business']
['130', 2.384931871, 'Indiana University Bloomington']
['58', 2.45567451, 'Universidad de Cantabria']
['126', 2.572707143, 'Utrecht University']
['16', 1.308696396, 'University of Strathclyde']
['3', 1.07276145, 'Norwegian University of Science & Technology (NTNU)']
['1013', 2.707349826, 'University Djillali Liabes Sidi Bel Abbes']
['1200', 2.715369036, 'University of New Orleans']
['850', 2.707349826, 'University Djillali Liabes Sidi Bel Abbes']
['744', 2.476509845, 'Drexel University']
['207', 2.428196145, 'Stanford University']
['920', 6.548206965, 'Shandong University of Science & Technology']
['1397', 6.548206965, 'Shandong University of Science & Technology']
['672', 6.548206965, 'Shandong University of Science & Technology']
['507', 6.548206965, 'Shandong University of Science & Technology']
['129', 2.002511924, 'New York University']
['437', 4.520608955, 'Quaid I Azam University']
['758', 7.756491398, 'University Djillali Liabes Sidi Bel Abbes']
['281', 3.747560714, 'King Abdulaziz University']
['45', 1.532920714, 'University of Science & Technology of China']
['419', 2.818098522, 'University of Liege']
['665', 3.164483529, 'Victor Babes University of Medicine & Pharmacy, Timisoara']
['306', 2.818098522, 'University of Liege']
['79', 2.016818626, 'Radboud University Nijmegen']
['242', 2.433032704, 'University of Tennessee Knoxville']
['503', 3.364009259, 'Edith Cowan University']
['152', 2.433032704, 'University of Tennessee Knoxville']
['23', 1.034618063, 'Huazhong University of Science & Technology']
['160', 2.531109375, 'University of Texas Austin']
['68', 2.452917391, 'Peking University']
['9', 1.728131441, 'China University of Geosciences - Beijing']
['447', 2.840545614, 'University of California Santa Cruz']
['632', 3.493583051, 'Universitat Jaume I']
['345', 2.814230153, 'Drexel University']
['61', 2.549385556, 'Stanford University']
['325', 2.234011475, 'University of Oxford']
['556', 2.728126923, 'Dublin City University']
['145', 1.812295, 'Western University (University of Western Ontario)']
['27', 1.441312203, 'University of Queensland']
['250', 2.28658, 'University of California Irvine']
['442', 2.484565217, 'University of Vienna']
['132', 2.27142013, 'Princeton University']
['25', 2.078192414, 'Massachusetts Institute of Technology (MIT)']
['931', 3.691692251, 'University of Dundee']
['1432', 3.691692251, 'University of Dundee']
['674', 3.691692251, 'University of Dundee']
['170', 1.71978837, 'University of Florence']
['1069', 6.551964134, 'University of Texas Rio Grande Valley']
['1343', 8.150791176, 'Indian Institute of Science Education & Research (IISER) - Thiruvananthapuram']
['906', 5.788409348, 'University of Urbino']
['803', 4.924725811, 'Gran Sasso Scientific Institute']
['414', 3.374450584, 'Stanford University']
['668', 4.218279412, 'Drexel University']
['220', 3.374450584, 'Stanford University']
['69', 3.374450584, 'Stanford University']
['755', 2.85427, 'Eindhoven University of Technology']
['1085', 4.164359016, 'Kutztown University - Pennsylvania']
['609', 2.85427, 'Eindhoven University of Technology']
['501', 2.85427, 'Eindhoven University of Technology']
['218', 1.893066032, 'University of Virginia']
['208', 3.7346, 'University of Bern']
['82', 3.095755, 'University of Georgia']
['17', 3.095755, 'University of Georgia']
['6', 2.918460902, 'Aarhus University']
['541', 8.205589189, 'Brandeis University']
['638', 8.205589189, 'Brandeis University']
['466', 6.427631527, 'Aga Khan University']
['373', 6.427631527, 'Aga Khan University']
['172', 3.480283871, 'University of Iceland']
['369', 4.97745, 'Hunan University']
['57', 3.480283871, 'University of Iceland']
['10', 1.568222074, 'Universite Toulouse III - Paul Sabatier']
['288', 3.56045625, 'Boston College']
['508', 3.56045625, 'Boston College']
['126', 3.037684028, 'Princeton University']
['12', 2.569365875, 'Harvard University']
['221', 4.933574286, 'RWTH Aachen University']
['491', 9.085784416, 'Karlsruhe Institute of Technology']
['129', 4.867813487, 'ETH Zurich']
['5', 1.500192473, 'Stanford University']
['304', 4.946542222, 'University of Texas Austin']
['545', 6.856162712, 'Pompeu Fabra University']
['195', 4.946542222, 'University of Texas Austin']
['21', 2.6486736, 'University of British Columbia']
['238', 3.225035294, 'Peking University']
['423', 3.225035294, 'Peking University']
['99', 2.481748603, 'Beihang University']
['23', 1.793172706, 'Tsinghua University']
['353', 1.940453846, 'McGill University']
['593', 2.42345, 'South China Normal University']
['217', 1.794352941, 'Universidad de Castilla-La Mancha']
['92', 1.570764846, 'Technical University of Denmark']
['279', 2.483343511, 'Australian National University']
['566', 3.117084746, 'University of Reading']
['161', 2.38878239, 'University of Aberdeen']
['8', 1.45411726, 'Delft University of Technology']

In [172]:
fin[0]

'Water Resources'

In [180]:
 final_list[0]

['Aerospace Engineering',
 1532,
 '50',
 '80',
 1.950663462,
 'York University - Canada',
 '25',
 '170',
 3.130375758,
 'Princeton University',
 '100',
 '28',
 1.939482,
 'University of Naples Federico II',
 '250',
 '7',
 1.654424466,
 'Harbin Institute of Technology']

In [ ]:
len()

In [181]:
for iiii in final_list:
    print(len(iiii))

18
0
0
22
18
18
22
18
18
18
18
22
18
22
18
18
18
18
18
18
18
22
18
22
18
18
18
0
18
22
18
18
18
18
18
22
22
18
18
18
14
18
18
18
18
18
18
22
18
18
18
18
0
18
18
18
18
18

In [182]:
rellll=[]
for i in final_list:
    if len(i)==0:
        continue
    while True:
        if len(i)!=22:
            i.append('NA')
        else:
            break
    rellll.append(i)

In [183]:
for ii in rellll:
    print(len(ii))

22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22

In [185]:
#################################### 保存文件 ###############################
result_latest=pd.DataFrame(np.array(rellll))#将pd.DataFrame(np.array(myarray))写入list
result_latest.to_csv("C:/Users/rk/Desktop/fawenyuzhi999.csv",index=False,encoding='GB18030')
result_latest

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,Aerospace Engineering,1532,50,80,1.950663462,York University - Canada,25,170,3.130375758,Princeton University,...,1.939482,University of Naples Federico II,250,7,1.654424466,Harbin Institute of Technology,NA,NA,NA,NA
1,Agricultural Sciences,4351,100,908,3.182104386,Princeton University,50,1352,3.182104386,Princeton University,...,3.051265116,Columbia University,200,543,2.524419685,Western Sydney University,500,187,1.964083296,University of California Berkeley
2,Atmospheric Science,3174,50,444,3.340315942,Montana State University Bozeman,25,732,5.28378,Universidade da Beira Interior,...,2.946729907,University of Montana,250,88,2.734927324,University of Exeter,NA,NA,NA,NA
3,Automation & Control,3197,100,214,5.318996703,Bohai University,50,462,5.757797647,Liaoning University of Technology,...,5.318996703,Bohai University,500,12,2.700051724,Southeast University - China,NA,NA,NA,NA
4,Biological Sciences,5120,200,1383,5.358596089,Tokyo Metropolitan University,150,1596,5.358596089,Tokyo Metropolitan University,...,5.358596089,Tokyo Metropolitan University,300,1109,5.358596089,Tokyo Metropolitan University,1000,449,3.703053066,Massachusetts Institute of Technology (MIT)
5,Biomedical Engineering,3461,100,347,2.347423967,City University of Hong Kong,50,600,2.783696296,China Pharmaceutical University,...,2.175826129,Suzhou University,500,15,2.173657371,Massachusetts Institute of Technology (MIT),NA,NA,NA,NA
6,Biotechnology,4144,100,558,5.227403943,Massachusetts Institute of Technology (MIT),50,970,5.713271739,Johns Hopkins Bloomberg School of Public Health,...,5.227403943,Massachusetts Institute of Technology (MIT),500,42,5.227403943,Massachusetts Institute of Technology (MIT),NA,NA,NA,NA
7,Business Administration,2967,50,493,4.156294118,University of Hawaii Manoa,100,229,2.930523077,Universidade Nova de Lisboa,...,2.522106787,Texas A&M University College Station,250,34,2.196307973,Indiana University Bloomington,NA,NA,NA,NA
8,Chemical Engineering,3879,100,551,3.485484076,University of Oxford,50,940,3.494803509,Chongqing Technology & Business University,...,3.485484076,University of Oxford,500,60,2.455116154,Nanyang Technological University,NA,NA,NA,NA
9,Chemistry,5009,200,1448,2.553708559,Kent State University,300,1151,2.553708559,Kent State University,...,2.553708559,Kent State University,500,787,2.491471959,Stanford University,1000,396,2.491471959,Stanford University
10,Civil Engineering,3425,100,351,7.966403571,University Djillali Liabes Sidi Bel Abbes,50,628,7.966403571,University Djillali Liabes Sidi Bel Abbes,...,4.60815,King Abdulaziz University,500,32,1.490899238,University of California Berkeley,NA,NA,NA,NA
11,Clinical Medicine,4689,200,1178,11.00893565,University of the Philippines Manila,150,1317,12.59830191,Sri Ramachandra University,...,8.729352695,Jordan University of Science & Technology,300,1013,8.729352695,Jordan University of Science & Technology,1000,531,4.035903759,Johns Hopkins Oncology Center
12,Communication,2071,25,357,4.475678788,University Hohenheim,50,191,3.151765169,Stanford University,...,2.985405147,Cornell University,125,48,2.985405147,Cornell University,NA,NA,NA,NA
13,Computer Science & Engineering,4565,150,723,5.484278788,Liaoning University of Technology,100,988,5.484278788,Liaoning University of Technology,...,3.88744867,McMaster University,750,103,2.495561034,King Abdulaziz University,NA,NA,NA,NA
14,Dentistry & Oral Sciences,2074,50,372,2.539948387,Laval University,25,559,2.6428,University of Maryland Baltimore County,...,2.106383274,KU Leuven,250,63,2.106383274,KU Leuven,NA,NA,NA,NA
15,Earth Sciences,3901,100,709,3.340219394,University of Waikato,150,536,3.340219394,University of Waikato,...,3.007104632,University of California Irvine,500,175,2.362922987,Princeton University,NA,NA,NA,NA
16,Ecology,3701,100,508,2.832976684,Universite de Versailles Saint-Quentin-En-Yvel...,50,765,3.424143333,City College of New York (CUNY),...,2.832976684,Universite de Versailles Saint-Quentin-En-Yvel...,500,84,2.304230653,Stanford University,NA,NA,NA,NA
17,Economics,3376,50,791,3.379353439,Dartmouth College,25,1136,5.598155556,New Mexico Institute of Mining Technology,...,3.379353439,Dartmouth College,250,160,2.946634594,Princeton University,NA,NA,NA,NA
18,Education,3687,50,672,3.239070588,University of Maine Orono,25,1023,3.239070588,University of Maine Orono,...,3.133507983,National Taiwan University of Science & Techno...,250,122,2.031730279,University of California San Francisco,NA,NA,NA,NA
19,Electrical & Electronic Engineering,4220,150,633,5.244737727,Victoria University,100,889,5.244737727,Victoria University,...,5.244737727,Victoria University,250,408,3.319216547,Lancaster University,750,109,2.812006193,University of Texas Austin
20,Energy Science & Engineering,4126,100,629,2.825443678,University of Nebraska Lincoln,50,1068,2.939057143,National University of Ireland (NUI) Galway,...,2.825443678,University of Nebraska Lincoln,500,104,2.769646308,Ecole Polytechnique Federale de Lausanne,NA,NA,NA,NA
21,Environmental Science & Engineering,4785,200,617,2.828912903,Suzhou University,150,773,2.828912903,Suzhou University,...,2.828912903,Suzhou University,300,393,2.659193482,Ecole Polytechnique Federale de Lausanne,1000,52,2.258311716,Stanford University
22,Finance,2116,50,252,3.983347549,University of Chicago,100,96,3.983347549,University of Chicago,...,3.983347549,University of Chicago,250,4,2.311131611,New York University,NA,NA,NA,NA
23,Food Science & Technology,3848,100,392,2.216272146,University of Massachusetts Amherst,50,714,2.216272146,University of Massachusetts Amherst,...,2.216272146,University of Massachusetts Amherst,500,24,1.822763062,South China University of Technology,NA,NA,NA,NA
24,Geography,3336,100,307,2.363906211,University of East Anglia,50,568,3.864839394,University of Denver,...,2.363906211,University of East Anglia,500,9,2.035294167,Utrecht University,NA,NA,NA,NA
25,Hospitality & Tourism Management,2018,25,300,3.021651724,Harbin Institute of Technology,50,117,2.691678652,University of Nevada Las Vegas,...,2.674308475,Virginia Polytechnic Institute & State University,125,25,2.27791195,Bournemouth University,NA,NA,NA,NA
26,Human Biological Sciences,4616,100,1205,3.603935885,Johns Hopkins Oncology Center,50,1644,3.603935885,Johns Hopkins Oncology Center,...,3.603935885,Johns Hopkins Oncology Center,200,836,3.603935885,Johns Hopkins Oncology Center,500,431,3.003217686,Massachusetts Institute of Technology (MIT)
27,Instruments Science & Technology,3718,100,346,3.678817483,King Abdulaziz University,50,667,5.827253125,Bogazici University,...,2.339700592,University of California San Diego,500,13,1.641369098,Harbin Institute of Technology,NA,NA,NA,NA
28,Law,2156,50,300,2.862083333,Iowa State University,25,514,4.222895,Carnegie Mellon University,...,2.862083333,Iowa State University,250,46,2.808960036,Yale University,NA,NA,NA,NA
29,Library & Information Science,2596,50,167,2.969271698,University of Quebec Montreal,25,372,4.523792,Ryerson University,...,2.727388321,University of Wolverhampton,250,1,1.624527953,Harvard University,NA,NA,NA,NA
30,Management,3700,50,821,3.260932203,University of Denver,100,470,2.535825714,Rice University,...,2.484022174,IU Kelley School of Business,250,130,2.384931871,Indiana University Bloomington,NA,NA,NA,NA
31,Marine/Ocean Engineering,1290,50,58,2.45567451,Universidad de Cantabria,25,126,2.572707143,Utrecht University,...,1.308696396,University of Strathclyde,250,3,1.07276145,Norwegian University of Science & Technology (...,NA,NA,NA,NA
32,Materials Science & Engineering,4714,200,1013,2.707349826,University Djillali Liabes Sidi Bel Abbes,150,1200,2.715369036,University of New Orleans,...,2.707349826,University Djillali Liabes Sidi Bel Abbes,300,744,2.476509845,Drexel University,1000,207,2.428196145,Stanford University
33,Mathematics,4045,100,920,6.548206965,Shandong University of Science & Technology,50,1397,6.548206965,Shandong University of Science & Technology,...,6.548206965,Shandong University of Science & Technology,200,507,6.548206965,Shandong University of Science & Technology,500,129,2.002511924,New York University
34,Mechanical Engineering,3646,100,437,4.520608955,Quaid I Azam University,50,758,7.756491398,University Djillali Liabes Sidi Bel Abbes,...,3.747560714,King Abdulaziz University,500,45,1.532920714,University of Science & Technology of China,NA,NA,NA,NA
35,Medical Technology,3332,100,419,2.818098522,University of Liege,50,665,3.164483529,Victor Babes University of Medicine & Pharmacy...,...,2.818098522,University of Liege,500,79,2.016818626,Radboud University Nijmegen,NA,NA,NA,NA
36,Metallurgical Engineering,3120,100,242,2.433032704,University of Tennessee Knoxville,50,503,3.364009259,Edith Cowan University,...,2.433032704,University of Tennessee Knoxville,500,23,1.034618063,Huazhong University of Science & Technology,NA,NA,NA,NA
37,Mining & Mineral Engineering,1734,25,160,2.531109375,University of Texas Austin,50,68,2.452917391,Peking University,...,1.728131441,China University of Geosciences - Beijing,NA,NA,NA,NA,NA,NA,NA,NA
38,Nanoscience & Nanotechnology,3831,150,447,2.840545614,University of California Santa Cruz,100,632,3.493583051,Universitat Jaume I,...,2.814230153,Drexel University,750,61,2.549385556,Stanford University,NA,NA,NA,NA
39,Nursing,2245,50,325,2.234011475,University of Oxford,25,556,2.728126923,Dublin City University,...,1.812295,Western University (University of Western Onta...,250,27,1.441312203,University of Queensland,NA,NA,NA,NA
40,Oceanography,2392,50,250,2.28658,University of California Irvine,25,442,2.484565217,University of Vienna,...,2.27142013,Princeton University,250,25,2.078192414,Massachusetts Institute of Technology (MIT),NA,NA,NA,NA
41,Pharmacy & Pharmaceutical Sciences,4404,100,931,3.691692251,University of Dundee,50,1432,3.691692251,University of Dundee,...,3.691692251,University of Dundee,500,170,1.71978837,University of Florence,NA,NA,NA,NA
42,Physics,4917,300,1069,6.551964134,University of Texas Rio Grande Valley,200,1343,8.150791176,Indian Institute of Science Education & Resear...,...,5.788409348,University of Urbino,500,803,4.924725811,Gran Sasso Scientific Institute,NA,NA,NA,NA
43,Political Sciences,2528,50,414,3.374450584,Stanford University,25,668,4.218279412,Drexel University,...,3.374450584,Stanford University,250,69,3.374450584,Stanford University,NA,NA,NA,NA
44,Psychology,3895,100,755,2.85427,Eindhoven University of Technology,50,1085,4.164359016,Kutztown University - Pennsylvania,...,2.85427,Eindhoven University of Technology,200,501,2.85427,Eindhoven University of Technology,500,218,1.893066032,University of Virginia
45,Public Administration,1752,25,208,3.7346,University of Bern,50,82,3.095755,University of Georgia,...,3.095755,University of Georgia,125,6,2.918460902,Aarhus University,NA,NA,NA,NA
46,Public Health,4559,250,541,8.205589189,Brandeis University,200,638,8.205589189,Brandeis University,...,6.427631527,Aga Khan University,400,373,6.427631527,Aga Khan University,NA,NA,NA,NA
47,Remote Sensing,2253,50,172,3.480283871,University of Iceland,25,369,4.97745,Hunan University,...,3.480283871,University of Iceland,250,10,1.568222074,Universite Toulouse III - Paul Sabatier,NA,NA,NA,NA
48,Sociology,2497,50,288,3.56045625,Boston College,25,508,3.56045625,Boston College,...,3.037684028,Princeton University,250,12,2.569365875,Harvard University,NA,NA,NA,NA
49,Statistics,3054,100,221,4.933574286,RWTH Aachen University,50,491,9.085784416,Karlsruhe Institute of Technology,...,4.867813487,ETH Zurich,500,5,1.500192473,Stanford University,NA,NA,NA,NA
50,Telecommunication Engineering,3170,100,304,4.946542222,University of Texas Austin,50,545,6.856162712,Pompeu Fabra University,...,4.946542222,University of Texas Austin,500,21,2.6486736,University of British Columbia,NA,NA,NA,NA
51,Transportation Science & Technology,2396,50,238,3.225035294,Peking University,25,423,3.225035294,Peking University,...,2.481748603,Beihang University,250,23,1.793172706,Tsinghua University,NA,NA,NA,NA
52,Veterinary Sciences,2782,50,353,1.940453846,McGill University,25,593,2.42345,South China Normal University,...,1.794352941,Universidad de Castilla-La Mancha,250,92,1.570764846,Technical University of Denmark,NA,NA,NA,NA
53,Water Resources,3669,100,279,2.483343511,Australian National University,50,566,3.117084746,University of Reading,...,2.38878239,University of Aberdeen,500,8,1.45411726,Delft University of Technology,NA,NA,NA,NA